server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Penting untuk React Router — semua route diarahkan ke index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
