version: "3.8"

services:

  backend:
    image: chandraniko/crud-backend:v1
    container_name: crud-backend
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    image: chandraniko/crud-frontend:v1
    container_name: crud-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
